spring:
  application:
    name: llxsMerchants
  datasource:
    url: jdbc:mysql://43.107.136.120:3306/passbook?autoReconnect=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 43.107.136.120:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4


logging:
  level:
    root: info
  file:
    name: llxs-merchants.log
